-- BETWEEN 

-- 1] WAQTD NAMES OF AN EMP HIRED AFTER 1981 AND BEFORE 1987
SELECT ename FROM emp 
WHERE hiredate BETWEEN "01-01-1981" AND  "31-12-1987";

-- 2] WAQTD DETAILS OF AN EMP EXCLUDING THE EMP'S WORKING IN DEPTNO 10 OR 20.
SELECT * FROM emp 
WHERE deptno NOT IN  (10,20);


-- 3] WAQTD DETILS OF AN EMP EXCEPT PRESIDENT OR MANAGER.
SELECT * 
FROM emp 
WHERE job NOT IN ("PRESIDENT" , "MANAGER");




