use compnay_db;

SELECT * FROM emp;
-- =======================
-- 	IN OPERATOR , NOT IN
-- =======================

-- 1] WAQTD NAMES OF AN EMP WHO IS WORKING IN DEPTNO 10,20
SELECT ename
FROM emp 
WHERE deptno IN (10,20);

-- 2] WAQTD SAL AND NAME OF EMP'S WHO IS NOT WORKING IN DEPTNO 10,30.
SELECT sal,ename 
FROM emp 
WHERE deptno NOT IN (10,30);

-- 3] WAQTD NAME & HIREDATE OF EMP'S WHOSE DESIGNATION IS CLERK,SALESMAN,MANAGER.
SELECT ename , hiredate 
FROM emp 
WHERE job IN ("CLERK" , "SALESMAN" , "MANAGER");

-- 4] WAQTD NAME & MANAGER NUMBER OF EMP'S EXCEPT FORD,MILLER,KING,JONES.
SELECT ename, mgr 
FROM emp 
WHERE ename IN ("FORD" , "MILLER" , "KING" , "JONES");

-- 5] WAQTD DETAILS OF AN EMP WHO IS EARNING 800,3000,2950.
SELECT * 
FROM emp 
WHERE sal IN (800,3000,2950);

-- 6] WAQTD NAME , SAL,ANNUAL SAL IF EMP IS NOT WORKING AS SALESMAN OR MANAGER IN DEPTNO 30.
SELECT  ename , sal , (sal * 12) AS Annual_Salary 
FROM emp 
WHERE job NOT IN ("SALESMAN"  , "MANAGER") AND deptno NOT IN (30) ;

-- 7] WAQTD NAME & COMMISSION OF EMP'S WHO IS HIRED ON 3/12/81 OR 28/9/81.
SELECT hiredate, ename , comm 
FROM emp 
WHERE hiredate IN ("1981-12-03","1981-09-28"); 

-- 8] WAQTD DETAILS OF AN EMP WORKING AS A MANAGER OR ANALYST EXCEPT DEPTNO 30.
SELECT * 
FROM emp 
WHERE job IN ("MANAGER","ANALYST") AND deptno != 30;

-- 9] WAQTF DETAILS OF AN EMP WHOSE MANAGER NUMBER IS 7902 OR 7566.
SELECT * 
FROM emp 
WHERE job IN ("MANAGER") AND mgr IN (7902,7566);
