use compnay_db;
SELECT * FROM emp;

-- 1] WAQTD NAMES OF AN EMP WHOSE NAME STARTS WITH CHARACTER 'A'.
SELECT ename 
from emp
WHERE ename LIKE 'A%';



-- 2] WAQTD NAMES OF AN EMP WHOSE DESIGNATION STARTS WITH CHARACTER 'S'.
SELECT job
from emp
WHERE job LIKE 'S%';

-- 3] WAQTD DETAILS OF AN EMP WHOSE NAME ENDS WITH CHARACTER 'T'
SELECT * 
from emp 
WHERE ename LIKE '%T';

-- 4] WAQTD DETAILS OF AN EMP WHOSE NAME HAS CHARACTER 'A'.
SELECT * 
FROM emp 
WHERE ename LIKE '%A%';

-- 5] WAQTD NAMES OF AN EMP WHO HAS CHARACTER 'A' IN SECOND PLACE OF HIS NAME.
SELECT ename 
FROM emp
WHERE ename LIKE '_A%';

-- 6] WAQTD DETAILS OF AN EMP HAVING 'A' IN SECOND LAST PLACE.
SELECT * 
FROM emp
WHERE ename LIKE '%A_';

-- 7] WAQTD DETAILS OF AN EMP HAVING 'S' IN THE LAST PLACE.
SELECT * 
FROM emp 
WHERE ename LIKE '%S';

-- 8] WAQTD NAMES OF AN EMP HAVING 'E' IN THE FOURTH PLACE.
SELECT ename 
FROM emp 
WHERE ename LIKE '___E%';


-- 9] WAQTD NAME OF AN EMP WHO HAVING CHARACTER 'A' IN FIRST PLACE & 'S' IN THE LAST PLACE.
SELECT ename 
FROM emp 
WHERE ename LIKE 'A%S';

-- 10] WAQTD NAME & SAL OF EMP'S IF THEY ARE EARNING 3 DIGIT SALARY.
SELECT ename , sal 
FROM emp
WHERE sal LIKE '___.__';

SELECT ename, sal 
FROM emp 
WHERE sal < 1000;

-- 11] WAQTD NAME & HIREDATE OF EMP IF THEY WERE HIRED IN THE YEAR 82
SELECT ename , hiredate 
FROM emp 
WHERE hiredate LIKE '__82-%-%';

-- 12] WAQTD DETAILS OF AN EMP WHO HAVING CHARACTER 'A' IN FIRST PLACE OR EMP'S IF THEY HAVE 'S' IN LAST PLACE.
SELECT * 
FROM emp
WHERE ename LIKE 'A%S';


-- 13] WAQTD NAME OF AN EMP WHO HAVING CHARACTER 'A' IN FIRST PLACE & WORKING IN DEPTNO 10 OR 20.
SELECT ename 
FROM emp 
WHERE ename LIKE 'A%' AND deptno IN (10,20);

-- 14] WAQTD NAME & SALARY OF EMP IF THEY ARE EARNING 4 DIGIT SALARY.
SELECT ename , sal 
FROM emp 
WHERE sal LIKE '____.%';

-- 15] WAQTD NAME, HIREDATE IF THEY ARE HIRED IN THE YEAR 81 & EARNING SALARY MORE THAN 2000.
SELECT ename , hiredate 
FROM emp
WHERE hiredate LIKE '__81-%-%';

-- 16] WAQTD DETAILS OF EMP'S IF THEY ARE HAVING STRING 
-- 'MAN' IN THEIR JOB.
SELECT * 
FROM emp 
WHERE job LIKE '%MAN%';

-- 17] WAQTD DETAILS OF AN EMP WHO HAVING CHARACTER 'A'  IN FIRST PLACE,   'D' IN SECOND PLACE & 'S' IN LAST PLACE.
SELECT * FROM emp
WHERE ename LIKE 'A%D_S';
-- 18] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 30 OR 40 & 
-- EARNING MORE THAN 2000.
SELECT * 
FROM emp 
WHERE  deptno in (30,40) AND sal > 2000; 

-- 19] WAQTD DETAILS OF AN EMP WORKING AS 'SALESMAN' OR 'MANAGER' IN DEPTNO 20 IN THE YEAR 83.
SELECT * 
FROM emp
WHERE job  IN ("SALESMAN" , "MANAGER") or deptno IN (20) AND hiredate LIKE ('__83-%-%');  

-- 20] WAQTD DETAILS OF EMP ALONG WITH ANNUAL SALARY IF 
-- THE ANNUAL SALARY IS MORE THAN RS.15000 IN DEPTNO 10 OR 20 EXCEPT EMP'S HIRED IN THE YEAR 82.
SELECT emp.* 
FROM emp 
WHERE (sal * 12) > 15000 AND deptno IN (10,20) AND hiredate NOT LIKE '__82-%-%';



