-- ===============
-- WHERE CLAUSE - 1
-- ===============

SELECT * FROM emp;

-- 1] WAQTD DETAILS OF SMITH.
SELECT * FROM emp 
WHERE ename = "SMITH";

-- 2] WAQTD DESIGNATION OF ALLEN.
SELECT job FROM emp
WHERE ename = "ALLEN";

-- 3] WAQTD SALARY OF SCOTT.
SELECT sal FROM emp 
WHERE ename = "SCOTT";

-- 4] WAQTD MILLER'S HIREDATE.
SELECT hiredate FROM emp 
WHERE ename = "MILLER";

-- 5] WAQTD DEPTTNO OF MARTIN.
SELECT deptno FROM emp WHERE ename = "MARTIN";

-- 6] WAQTD NAMES OF AN EMP WORKING AS SALESMAN.
SELECT ename FROM emp WHERE job = "SALESMAN";

-- 8] WAQTD NAME,JOB,SALARY, & HIREDATE OF PRESIDENT.
SELECT ename , job , sal , hiredate FROM emp WHERE job = "PRESIDENT";

-- 9] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 20.
SELECT ename FROM emp WHERE deptno = 20;

-- 10] WAQTD NAMES OF AN EMP EARNING 1250RPS.
SELECT ename FROM emp WHERE sal = 1250;

-- 11] WAQTD NAMES OF AN EMP EARNING COMMISSION OF 500RPS.
SELECT ename FROM emp WHERE comm > 500 ;

-- 12] WAQTD NAME, SAL, ANNUAL SAL OF EMP'S WORKING IN DEPTNO 30.
SELECT ename , sal , sal * 12 FROM emp WHERE deptno = 30;

-- 13] WAQTD DETAILS OF AN EMP EARNING MORE THAN 2000 RPS.
SELECT * FROM emp WHERE sal > 2000;

-- 14] WAQTD DETAILS OF AN EMP EARNING LESS THAN 3000 RPS.
SELECT * FROM emp WHERE sal < 3000;

-- 15] WAQTD NAMES OF AN EMP EARNING COMMISSION MORE THAN 500.
SELECT ename FROM emp WHERE comm > 500;

-- 16] WAQTD DETAILS OF AN EMP HIRED AFTER 1981.
SELECT * FROM emp WHERE hiredate > 1981;
