USE compnay_db;

-- 1] WAQTD DETAILS OF AN EMP HIRED BEFORE 1987.

SELECT * FROM emp WHERE hiredate < 1987;
SELECT * FROM emp;

-- 2] WAQTD NAMES OF AN EMP WORKING AS A CLERK & EARNING LESS THAN 1000.
SELECT ename FROM emp WHERE job = "CLERK" AND sal < 1000;

-- 3] WAQTD NAMES OF AN EMP WORKING AS SALESMAN IN DEPTNO 20.
SELECT ename FROM emp WHERE job = "SALESMAN" AND deptno = 20;

-- 4] WAQTD SALARY OF PRESIDENT.
SELECT sal FROM emp where job = "PRESIDENT";

-- 5] WAQTD NAMES OF AN EMP WORKING AS ANALYST.
SELECT ename FROM emp WHERE job = "ANALYST";

-- 6] WAQTD NAMES OF AN EMP EARNING LESS THAN 1000.
SELECT ename FROM emp WHERE sal < 1000;

-- 7] WAQTD NAMES OF AN EMP EARNING RS.3000.
SELECT ename FROM emp WHERE sal = 3000;

-- 8] WAQTD DETAILS OF AN EMP HIRED BEFORE 1981.44
SELECT * FROM emp WHERE hiredate < 1982;

-- 10] WAQTD NAMES OF AN EMP EARNING COMMISSION LESS THAN 300.
SELECT ename FROM emp WHERE comm < 300;

-- 11] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 10.
SELECT ename FROM emp WHERE deptno = 10;

-- 12] WAQTD NAMES OF AN EMP WORKING AS A CLERK & EARNING MORE THAN 1000.
SELECT ename FROM emp WHERE job = "CLERK" AND sal > 1000;

-- 13] WAQTD DETAILS OF AN EMP WORKING AS MANAGER IN DEPTNO 20
SELECT * FROM emp WHERE job = "MANAGER" AND deptno = 20;

-- 14] WAQTD DETAILS OF AN EMP WORKING AS CLERK & HIRED AFTER 1980.
SELECT * FROM emp WHERE job = "CLERK" AND hiredate > 1980;